import type { Agent } from '../types'

export const SEED_AGENTS: Agent[] = [
  {
    id: 'customs-7',
    name: 'Customs-7',
    role: 'Clearance',
    status: 'running',
    nodeId: 'customs_clearance',
    task: 'Review ISF / entries',
    tokens: 18220,
    lastAt: new Date().toISOString(),
  },
  {
    id: 'extract-3',
    name: 'Extract-3',
    role: 'Documents',
    status: 'running',
    nodeId: 'document_extraction',
    task: 'OCR shipment packet',
    tokens: 44102,
    lastAt: new Date().toISOString(),
  },
  {
    id: 'except-1',
    name: 'Except-1',
    role: 'Exceptions',
    status: 'running',
    nodeId: 'exceptions',
    task: 'Triage vessel delay',
    tokens: 9033,
    lastAt: new Date().toISOString(),
  },
  {
    id: 'quote-9',
    name: 'Quote-9',
    role: 'Finance',
    status: 'idle',
    nodeId: 'quotes',
    task: 'Idle · waiting rate card',
    tokens: 2201,
    lastAt: new Date().toISOString(),
  },
  {
    id: 'notify-2',
    name: 'Notify-2',
    role: 'Comms',
    status: 'running',
    nodeId: 'external_messages',
    task: 'Customer notice SLA',
    tokens: 15670,
    lastAt: new Date().toISOString(),
  },
  {
    id: 'yard-4',
    name: 'Yard-4',
    role: 'Equipment',
    status: 'blocked',
    nodeId: 'chassis',
    task: 'Blocked · chassis shortage',
    tokens: 880,
    lastAt: new Date().toISOString(),
  },
  {
    id: 'route-5',
    name: 'Route-5',
    role: 'Planning',
    status: 'running',
    nodeId: 'route',
    task: 'Recompute transshipment',
    tokens: 12044,
    lastAt: new Date().toISOString(),
  },
  {
    id: 'recon-8',
    name: 'Recon-8',
    role: 'Finance',
    status: 'idle',
    nodeId: 'invoices',
    task: 'Idle · next invoice batch',
    tokens: 6102,
    lastAt: new Date().toISOString(),
  },
]
